@server = http://localhost:4004

## GET Groups
GET {{server}}/service/Projects/Groups

GET {{server}}/myService2/Groups

## GET Groups with filter parameters
GET {{server}}/service/Projects/Groups?$filter=type eq 'PROJECT_PARTNER'

## GET Groups and associated Group memberships
GET {{server}}/service/Projects/Groups?$expand=toGroupMemberships

## GET GroupMemberships
GET {{server}}/service/Projects/GroupMemberships

## GET GroupMemberships and associated Group
GET {{server}}/service/Projects/GroupMemberships?$expand=toGroup



### Call myservice2 from service/Projects

GET {{server}}/myService2/getProjects()

GET {{server}}/service/Projects/getProjects()

GET {{server}}/service/Projects/getProjectsWithHighPriorityTasks()



### Mashup of Project Demands

## GET Project Demands (local entity)
GET {{server}}/myService2/ProjectDemandLink

GET {{server}}/myService2/ProjDemand

## GET ProjectDemands from local service and associated demand details from external service
GET {{server}}/myService2/ProjectDemandLink?$expand=projectDemand


## GET Project demand mocked
GET {{server}}/odata/v4/project-demand/A_ProjectDemand


## GET ProjectDemandStatus
GET {{server}}/service/Projects/ProjectDemandStatus